const CLOUDFLARE_WORKER = "Cloudflare Worker";
const DISCORD_SERVICE = "Discord Service";
const BAD_TOKEN = "BAD.JWT.TOKEN";
const CRON_JOB_HANDLER = "Cron Job Handler";

const Services = {
  CLOUDFLARE_WORKER: CLOUDFLARE_WORKER,
  DISCORD_SERVICE: DISCORD_SERVICE,
  CRON_JOB_HANDLER: CRON_JOB_HANDLER,
};

module.exports = { CLOUDFLARE_WORKER, BAD_TOKEN, CRON_JOB_HANDLER, Services, DISCORD_SERVICE };
