const logType = {
  PROFILE_DIFF_APPROVED: "PROFILE_DIFF_APPROVED",
  PROFILE_DIFF_REJECTED: "PROFILE_DIFF_REJECTED",
  CLOUDFLARE_CACHE_PURGED: "CLOUDFLARE_CACHE_PURGED",
  APPLICATION_UPDATED: "USER_APPLICATION_UPDATED",
  EVENTS_REMOVE_PEER: "EVENTS_REMOVE_PEER",
  APPLICATION_ADDED: "USER_APPLICATION_ADDED"
};

module.exports = { logType };
