const logType = {
  PROFILE_DIFF_APPROVED: "PROFILE_DIFF_APPROVED",
  PROFILE_DIFF_REJECTED: "PROFILE_DIFF_REJECTED",
  CLOUDFLARE_CACHE_PURGED: "CLOUDFLARE_CACHE_PURGED",
};

module.exports = { logType };
