export const MAX_WRONG_ATTEMPTS_BY_IP_PER_MINUTE = 5;
export const MAX_WRONG_ATTEMPTS_BY_IP_PER_DAY = 100;
export const MAX_REQUEST_WINDOW_BY_IP_PER_MINUTE = 30;
export const MAX_REQUEST_WINDOW_BY_IP_PER_HOUR = 60 * 60 * 24;
export const BLOCK_DURATION_WINDOW_BY_IP_PER_MINUTE = 60 * 10;
export const BLOCK_DURATION_WINDOW_BY_IP_PER_HOUR = 60 * 60 * 24;
export const MAX_WRONG_ATTEMPTS_BY_IP_PER_MINUTE_KEY_PREFIX = "login_fail_by_ip_per_minute";
export const MAX_WRONG_ATTEMPTS_BY_IP_PER_DAY_KEY_PREFIX = "login_fail_by_ip_per_day";
