const TASK_REQUEST_STATUS = {
  WAITING: "WAITING",
  APPROVED: "APPROVED",
  PENDING: "PENDING",
  DENIED: "DENIED",
};

const TASK_REQUEST_TYPE = {
  ASSIGNMENT: "ASSIGNMENT",
  CREATION: "CREATION",
};

const MIGRATION_TYPE = {
  ADD_NEW_FIELDS: "add-new-fields",
  REMOVE_OLD_FIELDS: "remove-redundant-fields",
};
module.exports = { TASK_REQUEST_STATUS, TASK_REQUEST_TYPE, MIGRATION_TYPE };
