const TASK_TYPE = {
  FEATURE: 'feature',
  GROUP: 'group',
  STORY: 'story'
}

const TASK_STATUS = {
  ACTIVE: 'IN_PROGRESS',
  ASSIGNED: 'ASSIGNED',
  BLOCKED: 'BLOCKED',
  COMPLETED: 'COMPLETED',
  UNASSIGNED: 'AVAILABLE',
  SMOKE_TESTING: 'SMOKE_TESTING',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  IN_REVIEW: 'IN_REVIEW',
  APPROVED: 'APPROVED',
  MERGED: 'MERGED',
  SANITY_CHECK: 'SANITY_CHECK',
  REGRESSION_CHECK: 'REGRESSION_CHECK',
  RELEASED: 'RELEASED',
  VERIFIED: 'VERIFIED'
}

module.exports = { TASK_TYPE, TASK_STATUS }
