const TASK_REQUEST_STATUS = {
  WAITING: "WAITING",
  APPROVED: "APPROVED",
  PENDING: "PENDING",
  DENIED: "DENIED",
};

const TASK_REQUEST_TYPE = {
  ASSIGNMENT: "ASSIGNMENT",
  CREATION: "CREATION",
};

module.exports = { TASK_REQUEST_STATUS, TASK_REQUEST_TYPE };
