const CURRENCY_TYPES = { DINERO: 'dinero', NEELAM: 'neelam' }

module.exports = {
  ...CURRENCY_TYPES,
  INITIAL_WALLET: {
    dinero: 1000
  },
  SUPPORTED_CURRENCIES: [CURRENCY_TYPES.DINERO, CURRENCY_TYPES.NEELAM]
}
