import express from "express";
import { devFlagMiddleware } from "../middlewares/devFlag.js";

export const appRoutes = express.Router();

import awsAccess from "./awsAccess.js";
import answers from "./answers.js";
import auctions from "./auctions.js";
import arts from "./arts.js";
import auth from "./auth.js";
import badge from "./badges.js";
import challenges from "./challenges.js";
import contributions from "./contributions.js";
import healthCheck from "./healthCheck.js";
import logs from "./logs.js";
import members from "./members.js";
import pullRequests from "./pullrequests.js";
import questions from "./questions.js";
import stocks from "./stocks.js";
import tasks from "./tasks.js";
import taskRequests from "./taskRequests.js";
import trading from "./trading.js";
import userStatus from "./userStatus.js";
import users from "./users.js";
import profileDiffs from "./profileDiffs.js";
import wallets from "./wallets.js";
import extensionRequests from "./extensionRequests.js";
import tags from "./tags.js";
import levels from "./levels.js";
import items from "./items.js";
import cloudflareCache from "./cloudflareCache.js";
import externalAccounts from "./external-accounts.js";
import events from "./events.js";
import discordActions from "./discordactions.js";
import issues from "./issues.js";
import progresses from "./progresses.js";
import monitor from "./monitor.js";
import staging from "./staging.js";
import applications from "./applications.js";
import fcmToken from "./fcmToken.js";
import notify from "./notify.js";
import goals from "./goals.js";
import invites from "./invites.js";
import requests from "./requests.js";
import subscription from "./subscription.js";

appRoutes.use("/aws/groups", devFlagMiddleware, awsAccess);
appRoutes.use("/answers", answers);
appRoutes.use("/auctions", auctions);
appRoutes.use("/arts", arts);
appRoutes.use("/auth", auth);
appRoutes.use("/auth", auth);
appRoutes.use("/badges", badge);
appRoutes.use("/challenges", challenges);
appRoutes.use("/contributions", contributions);
appRoutes.use("/healthcheck", healthCheck);
appRoutes.use("/logs", logs);
appRoutes.use("/members", members);
appRoutes.use("/pullrequests", pullRequests);
appRoutes.use("/questions", questions);
appRoutes.use("/stocks", stocks);
appRoutes.use("/tasks", tasks);
appRoutes.use("/taskRequests", taskRequests);
appRoutes.use("/trade", trading);
appRoutes.use("/users/status", userStatus);
appRoutes.use("/users", users);
appRoutes.use("/profileDiffs", profileDiffs);
appRoutes.use("/wallet", wallets);
appRoutes.use("/extension-requests", extensionRequests);
appRoutes.use("/tags", tags);
appRoutes.use("/levels", levels);
appRoutes.use("/items", items);
appRoutes.use("/cache", cloudflareCache);
appRoutes.use("/external-accounts", externalAccounts);
appRoutes.use("/events", events);
appRoutes.use("/discord-actions", discordActions);
appRoutes.use("/issues", issues);
appRoutes.use("/progresses", progresses);
appRoutes.use("/monitor", monitor);
appRoutes.use("/staging", staging);
appRoutes.use("/applications", applications);
appRoutes.use("/v1/fcm-tokens", fcmToken);
appRoutes.use("/v1/notifications", notify);
appRoutes.use("/goals", goals);
appRoutes.use("/invites", invites);
appRoutes.use("/requests", requests);
appRoutes.use("/subscription", devFlagMiddleware, subscription);
