import express from "express";
import { devFlagMiddleware } from "../middlewares/devFlag.js";

export const appRoutes = express.Router();

appRoutes.use("/aws/groups", devFlagMiddleware, require("./awsAccess"))
appRoutes.use("/answers", require("./answers"));
appRoutes.use("/auctions", require("./auctions"));
appRoutes.use("/arts", require("./arts"));
appRoutes.use("/auth", require("./auth"));
appRoutes.use("/badges", require("./badges.js"));
appRoutes.use("/challenges", require("./challenges"));
appRoutes.use("/contributions", require("./contributions"));
appRoutes.use("/healthcheck", require("./healthCheck"));
appRoutes.use("/logs", require("./logs.js"));
appRoutes.use("/members", require("./members.js"));
appRoutes.use("/pullrequests", require("./pullrequests"));
appRoutes.use("/questions", require("./questions"));
appRoutes.use("/stocks", require("./stocks.js"));
appRoutes.use("/tasks", require("./tasks.js"));
appRoutes.use("/taskRequests", require("./taskRequests"));
appRoutes.use("/trade", require("./trading"));
appRoutes.use("/users/status", require("./userStatus.js"));
appRoutes.use("/users", require("./users.js"));
appRoutes.use("/profileDiffs", require("./profileDiffs.js"));
appRoutes.use("/wallet", require("./wallets.js"));
appRoutes.use("/extension-requests", require("./extensionRequests"));
appRoutes.use("/tags", require("./tags.js"));
appRoutes.use("/levels", require("./levels.js"));
appRoutes.use("/items", require("./items.js"));
appRoutes.use("/cache", require("./cloudflareCache"));
appRoutes.use("/external-accounts", require("./external-accounts.js"));
appRoutes.use("/events", require("./events.js"));
appRoutes.use("/discord-actions", require("./discordactions.js"));
appRoutes.use("/issues", require("./issues"));
appRoutes.use("/progresses", require("./progresses"));
appRoutes.use("/monitor", require("./monitor.js"));
appRoutes.use("/staging", require("./staging"));
appRoutes.use("/applications", require("./applications"));
appRoutes.use("/v1/fcm-tokens", require("./fcmToken.js"));
appRoutes.use("/v1/notifications", require("./notify"));
appRoutes.use("/goals", require("./goals"));
appRoutes.use("/invites", require("./invites"));
appRoutes.use("/requests", require("./requests"));
appRoutes.use("/subscription", devFlagMiddleware, require("./subscription"));
