import express from "express";
import { devFlagMiddleware } from "../middlewares/devFlag";

// ESM imports
import awsAccessRouter from "./awsAccess.js";
import answersRouter from "./answers.js";
import auctionsRouter from "./auctions.js";
import artsRouter from "./arts.js";
import authRouter from "./auth.js";
import badgesRouter from "./badges.js";
import challengesRouter from "./challenges.js";
import contributionsRouter from "./contributions.js";
import healthCheckRouter from "./healthCheck.js";
import logsRouter from "./logs.js";
import membersRouter from "./members.js";
import pullrequestsRouter from "./pullrequests.js";
import questionsRouter from "./questions.js";
import stocksRouter from "./stocks.js";
import tasksRouter from "./tasks.js";
import taskRequestsRouter from "./taskRequests.js";
import tradingRouter from "./trading.js";
import userStatusRouter from "./userStatus.js";
import usersRouter from "./users.js";
import profileDiffsRouter from "./profileDiffs.js";
import walletsRouter from "./wallets.js";
import extensionRequestsRouter from "./extensionRequests.js";
import tagsRouter from "./tags.js";
import levelsRouter from "./levels.js";
import itemsRouter from "./items.js";
import cloudflareCacheRouter from "./cloudflareCache.js";
import externalAccountsRouter from "./external-accounts.js";
import eventsRouter from "./events.js";
import discordactionsRouter from "./discordactions.js";
import issuesRouter from "./issues.js";
import progressesRouter from "./progresses.js";
import monitorRouter from "./monitor.js";
import stagingRouter from "./staging.js";
import applicationsRouter from "./applications.js";
import fcmTokenRouter from "./fcmToken.js";
import notifyRouter from "./notify.js";
import goalsRouter from "./goals.js";
import invitesRouter from "./invites.js";
import requestsRouter from "./requests.js";
import impersonationRouter from "./impersonation.js";
import subscriptionRouter from "./subscription.js";

const appRoutes = express.Router();

appRoutes.use("/aws/groups", devFlagMiddleware, awsAccessRouter);
appRoutes.use("/answers", answersRouter);
appRoutes.use("/auctions", auctionsRouter);
appRoutes.use("/arts", artsRouter);
appRoutes.use("/auth", authRouter);
appRoutes.use("/badges", badgesRouter);
appRoutes.use("/challenges", challengesRouter);
appRoutes.use("/contributions", contributionsRouter);
appRoutes.use("/healthcheck", healthCheckRouter);
appRoutes.use("/logs", logsRouter);
appRoutes.use("/members", membersRouter);
appRoutes.use("/pullrequests", pullrequestsRouter);
appRoutes.use("/questions", questionsRouter);
appRoutes.use("/stocks", stocksRouter);
appRoutes.use("/tasks", tasksRouter);
appRoutes.use("/taskRequests", taskRequestsRouter);
appRoutes.use("/trade", tradingRouter);
appRoutes.use("/users/status", userStatusRouter);
appRoutes.use("/users", usersRouter);
appRoutes.use("/profileDiffs", profileDiffsRouter);
appRoutes.use("/wallet", walletsRouter);
appRoutes.use("/extension-requests", extensionRequestsRouter);
appRoutes.use("/tags", tagsRouter);
appRoutes.use("/levels", levelsRouter);
appRoutes.use("/items", itemsRouter);
appRoutes.use("/cache", cloudflareCacheRouter);
appRoutes.use("/external-accounts", externalAccountsRouter);
appRoutes.use("/events", eventsRouter);
appRoutes.use("/discord-actions", discordactionsRouter);
appRoutes.use("/issues", issuesRouter);
appRoutes.use("/progresses", progressesRouter);
appRoutes.use("/monitor", monitorRouter);
appRoutes.use("/staging", stagingRouter);
appRoutes.use("/applications", applicationsRouter);
appRoutes.use("/v1/fcm-tokens", fcmTokenRouter);
appRoutes.use("/v1/notifications", notifyRouter);
appRoutes.use("/goals", goalsRouter);
appRoutes.use("/invites", invitesRouter);
appRoutes.use("/requests", requestsRouter);
appRoutes.use("/impersonation", devFlagMiddleware, impersonationRouter);
appRoutes.use("/subscription", devFlagMiddleware, subscriptionRouter);

export { appRoutes };
